hydra:
  run:
    dir: ${env.save_dir}/hydra

name: ???  # name of experiment run
predictions: null

env:
  save_dir: .results/${name}/${now:%Y-%m-%d_%H-%M-%S}
  seed: 1463
  precision: "medium"
  logger:
    _target_: lightning.pytorch.loggers.NeptuneLogger
    name: ${name}
    project: "3dlg-hcvc-atwang/3d-ovfgvg-evaluation"
    dependencies: pyproject.toml
    source_files:
      - "ovfgvg/**/*.py"
      - "config/**/*.yaml"

defaults:
  - _self_
  - data: scanrefer
  - model: predictions
